name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "::add-matcher::.github/unix-problem-matcher.json"
    - run: |
        wget https://github.com/jgm/pandoc/releases/download/2.9.1.1/pandoc-2.9.1.1-1-amd64.deb
        sudo sh -c "yes | dpkg -i pandoc-2.9.1.1-1-amd64.deb"
    - run: npm ci
    - run: npm run build -s
    - run: npm run validate -s
    - run: npm run test -s -- -tap | node .github/avatap2gh.js
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run lint -s
